<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Ace-PC" name="com.toolsqa.framework.tests.TestNG_003" tests="4" failures="1" timestamp="12 Oct 2015 22:32:16 GMT" time="0.047" errors="0">
  <testcase name="run3" time="0.000" classname="com.toolsqa.framework.tests.TestNG_003"/>
  <testcase name="run4" time="0.031" classname="com.toolsqa.framework.tests.TestNG_003">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.toolsqa.framework.pageobjectmodel.StoreLoginPage.<init>(StoreLoginPage.java:17)
	at com.toolsqa.framework.pageobjectmodel.StoreLoginPage.<init>(StoreLoginPage.java:11)
	at com.toolsqa.framework.tests.TestNG_001.testRun1(TestNG_001.java:17)
	at com.toolsqa.framework.tests.TestNG_003.run4(TestNG_003.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- run4 -->
  <testcase name="run1" time="0.000" classname="com.toolsqa.framework.tests.TestNG_003"/>
  <testcase name="validateDiscountText" time="0.016" classname="com.toolsqa.framework.tests.TestNG_003"/>
</testsuite> <!-- com.toolsqa.framework.tests.TestNG_003 -->
